### PR TITLE
Use DefaultSettings for curl proxy settings, dynamic proxy/UA settings

### PR DESCRIPTION
**Pull request by tholu**
Should fix issue #123 

Changes:
- Updated DefaultSettings to include curl proxy settings
- Use DefaultSettings in HttpRequest helper
- Update .gitignore for .idea folder and fix composer.json intendation

### CODE REVIEW

**Comment by tholu** [comment]
@eyecatchup Are you currently accepting pull requests?

**Comment by prionkor** [comment]
Do we have something similar for user agent?

**Comment by tholu** [comment]
@prionkor See my last commit to this pull request, which allows to set it dynamically: https://github.com/eyecatchup/SEOstats/pull/129/commits/be4c91dd5b44e6912982ac038ef25eb176a54605

You can use my fork in composer until this pull request is accepted.

**Comment by prionkor** [comment]
Got it! Thanks for your quick response :)

**Pull request merged**
